package com.f4.feed.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class FeedItemAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFeedItemAllPropertiesEquals(FeedItem expected, FeedItem actual) {
        assertFeedItemAutoGeneratedPropertiesEquals(expected, actual);
        assertFeedItemAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFeedItemAllUpdatablePropertiesEquals(FeedItem expected, FeedItem actual) {
        assertFeedItemUpdatableFieldsEquals(expected, actual);
        assertFeedItemUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFeedItemAutoGeneratedPropertiesEquals(FeedItem expected, FeedItem actual) {
        assertThat(actual)
            .as("Verify FeedItem auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFeedItemUpdatableFieldsEquals(FeedItem expected, FeedItem actual) {
        assertThat(actual)
            .as("Verify FeedItem relevant properties")
            .satisfies(a -> assertThat(a.getUserId()).as("check userId").isEqualTo(expected.getUserId()))
            .satisfies(a -> assertThat(a.getReelId()).as("check reelId").isEqualTo(expected.getReelId()))
            .satisfies(a -> assertThat(a.getTimestamp()).as("check timestamp").isEqualTo(expected.getTimestamp()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFeedItemUpdatableRelationshipsEquals(FeedItem expected, FeedItem actual) {
        // empty method
    }
}
